In [5]:
import torch

In [2]:
x=torch.Tensor(5,3)
print(x)


 2.6213e-09  3.0880e-41 -6.9461e-22
 4.5859e-41 -6.8030e-22  4.5859e-41
 1.2742e-09  3.0880e-41  1.2742e-09
 3.0880e-41 -5.4658e-15  4.5859e-41
-6.6892e-22  4.5859e-41 -6.6892e-22
[torch.FloatTensor of size 5x3]



随机初始化矩阵

In [3]:
a=torch.Tensor([[2,3],[4,8],[4,7]])
print('a is:{}'.format(a))
print('a size is{}'.format(a.size()))

a is:
 2  3
 4  8
 4  7
[torch.FloatTensor of size 3x2]

a size istorch.Size([3, 2])


In [8]:
a=torch.LongTensor([[2,3],[4,8],[4,7]])
print('a is :{}'.format(a))
a[0,1]=100
print('new a is:{}'.format(a))

a is :
 2  3
 4  8
 4  7
[torch.LongTensor of size 3x2]

new a is:
   2  100
   4    8
   4    7
[torch.LongTensor of size 3x2]



In [3]:
x=torch.rand(5,3)
print(x)


 0.3131  0.2971  0.1192
 0.3277  0.1469  0.8987
 0.9717  0.6556  0.0266
 0.2831  0.9307  0.4036
 0.7128  0.5255  0.3762
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())

torch.Size([5, 3])


#### Operations运算

In [6]:
y=torch.rand(5,3)
print y
print(x+y)


 0.5241  0.6272  0.9633
 0.3065  0.2082  0.1616
 0.9734  0.5337  0.5812
 0.2415  0.8136  0.5416
 0.3037  0.1478  0.8749
[torch.FloatTensor of size 5x3]


 0.8372  0.9243  1.0825
 0.6342  0.3551  1.0602
 1.9451  1.1893  0.6077
 0.5246  1.7443  0.9452
 1.0165  0.6734  1.2511
[torch.FloatTensor of size 5x3]



In [7]:
print torch.add(x,y)


 0.8372  0.9243  1.0825
 0.6342  0.3551  1.0602
 1.9451  1.1893  0.6077
 0.5246  1.7443  0.9452
 1.0165  0.6734  1.2511
[torch.FloatTensor of size 5x3]



任何原地改变tensor的运算后边会后缀一个“_”,例如：x.copy_(y),x.t_(),会改变x的值。

In [8]:
y.add_(x)
print(y)


 0.8372  0.9243  1.0825
 0.6342  0.3551  1.0602
 1.9451  1.1893  0.6077
 0.5246  1.7443  0.9452
 1.0165  0.6734  1.2511
[torch.FloatTensor of size 5x3]



In [9]:
print(y[:,1])


 0.9243
 0.3551
 1.1893
 1.7443
 0.6734
[torch.FloatTensor of size 5]



#### 与numpy之间的转换

In [10]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[1. 1. 1. 1. 1.]


In [11]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


torch的Tensor和numpy的array分享底层的内存地址，所以改变其中一个就会改变另一个。

In [11]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [10]:
import torch
import numpy as np
#from torch to numpy
a=torch.randn((3,2))
b=a.numpy()
print('torch is {}'.format(a))
print('numpy is {}'.format(b))
#from numpy to torch
c=np.array([[2,3],[4,5]])
d=torch.from_numpy(c)
print('numpy is {}'.format(c))
print('torch is {}'.format(d))
#change torch's type
d_float=d.float()
print('float torch is {}'.format(d_float))

torch is 
-0.9863  0.6846
 0.8523  1.6950
-0.3032  0.4702
[torch.FloatTensor of size 3x2]

numpy is [[-0.9863318   0.6846314 ]
 [ 0.85225064  1.6950094 ]
 [-0.30324295  0.47020766]]
numpy is [[2 3]
 [4 5]]
torch is 
 2  3
 4  5
[torch.LongTensor of size 2x2]

float torch is 
 2  3
 4  5
[torch.FloatTensor of size 2x2]



#### cuda tensors
通过cuda，tensors可以被移动到gpu

In [14]:
x=torch.Tensor([[2,3],[4,5]])
if torch.cuda.is_available():
    x=x.cuda();
print(x)


 2  3
 4  5
[torch.cuda.FloatTensor of size 2x2 (GPU 0)]



## Summary
配了几天终于把环境配好了，首先学习了pytorch的矩阵运算，以及和numpy之间的转换，个人感觉和numpy差不多。最后运行转换成cuda时遇到了问题`RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:301`打算明天再看了，虽然只尝试了一些很简单的sample，就当做对环境的测试吧:)